### index handler

GET http://localhost:8081/
### get user
GET http://localhost:8081/user

### update user
PATCH  http://localhost:8081/update
Content-Type: application/json

{
    "age": 20,
    "skills": ["java", "python", "nodejs", "Rust"]
}

### invalid request
PATCH http://localhost:8081/update
Content-Type: application/json

{
    "age": 20,
    "skills": "java"
}


### shortener
POST http://localhost:8080/
Content-Type: application/json

{
    "url": "https://www.baidu1.com/"
}

### get-url
GET http://localhost:9876/YlC0pW

### get-url refactor
GET http://0.0.0.0:8080/YntiKO/1
